### ISSUE TITLE
Chapitre ggplot2

### ISSUE THREAD

**Issue by larmarange** [larmarange/analyse-R#13]

**Comment by larmarange** [comment]
- http://bioinfo-fr.net/guide-de-demarrage-pour-ggplot2-un-package-graphique-pour-r

**Comment by larmarange** [comment]
https://learnr.files.wordpress.com/2009/08/latbook.pdf

**Comment by briatte** [comment]
Voici une [suggestion de chapitre](https://github.com/larmarange/analyse-R/pull/36), basée sur un exemple de cours. Je suppose que ça va dans "Prise en main". J'ai aussi mis un petit peu de `lattice`.

En fait, je serais d'avis de faire _tous_ les graphiques avec `ggplot2`, pour en rentabiliser l'apprentissage. Même les graphiques de `survey` peuvent être reproduits avec `ggplot2`, ce qui oblige au passage à comprendre ce que `survey` produit : autrement dit, c'est aussi une bonne méthode d'apprentissage :)

**Comment by larmarange** [comment]
Tout d'abord un grand merci pour cette proposition. ;-)))

Je pensais mettre le chapitre sur ggplot dans _Avancé_, pour une question de progression de cours. 

Ceci étant dit, ça pourrait être pas mal de reprendre tous les chapitres avec `ggplot2` par défaut (et en présentant les cas particuliers comme des exceptions). 

Auquel cas, peut-être faudrait-il commencer par mettre à jour le chapitre _Statistique univariée_ puis (après _Manipulation de données_ je pense car `ggplot2` requiert de savoir jongler avec des data.frame) un chapitre introductif, qui présenterait la philosophie de `ggplot` et la syntaxe des graphiques.

Il faudrait ensuite mettre à jour les différents chapitres de la section _Analyses_. Enfin, regrouper dans un chapitre de la section _Avancé_ une présentation plus détaillée sur comment personnaliser les légendes, les thèmes etc.

Ca pose aussi la question de savoir s'il faurait faire un chapitre (section avancée) sur les graphs de bases en **R** (ce qu'on aura retiré des autres chapitres), voir un truc un peu sur le modèle de https://learnr.files.wordpress.com/2009/08/latbook.pdf  qui présente côte à côte la syntaxe de base **R**, la syntaxe **ggplot** et la syntaxe **lattice** ?

**Comment by briatte** [comment]
> Ceci étant dit, ça pourrait être pas mal de reprendre tous les chapitres avec `ggplot2` par défaut (et en présentant les cas particuliers comme des exceptions).

Plus généralement, je serais d'avis de faire tout ce qu'on peut avec les packages du Hadleyverse, qui sont rapides et cohérents entre eux :
- `dplyr` (et donc la classe `data_frame` dès que possible, plus d'emmerdes avec `stringsAsFactors`)
- `reshape2` (installé avec `ggplot2`), ou alors `tidyr` ? (je ne l'aime pas trop celui-là)
- `ggplot2`, of course
- `haven`, `readr`, `readxl`
- [`broom`](https://github.com/hadley/broom) (hyper pratique)
- `rvest` et `httr` pour le scraping
- `stringr` et `lubridate` pour les chaînes de texte / dates

Mettre à jour les chapitres : facile, surtout si on s'y prend à plusieurs.

Faire une annexe R base / lattice / ggplot2 : bof. Je serais plutôt d'avis de faire un choix et de forcer ce choix sur les lecteurs, et d'être extensif sur les sujets couverts plutôt que sur les packages couverts.

**Comment by larmarange** [comment]
C'est globalement une bonne idée.  Je serai aussi partisan de mettre `data.table` en avant car très puissant et compatible avec tous ces packages.

Par ailleurs, la relecture/récriture des chapitres sera aussi une occasion de voir s'il y aurait des suggestions d'amélioration à faire pour `questionr`.

Il me semble qu'il faudrait déjà commencer par la section _Prise en main_.  On pourra reprendre la présentation d'analyse-R et peut-être prévoir une introduction au _Hadleyverse_ une fois le travail bien avancé.

**Comment by briatte** [comment]
Je viens de commit une version mise à jour du chapitre, qui respecte les conventions dont on vient de discuter. Je rédige très rapidement un chapitre "Graphiques de base" sur la base de ton chapitre "Exporter des graphiques".

**Comment by larmarange** [comment]
Tu veux mettre quoi dans le chapitre "Graphiques de base" ?

Ne serait-ce pas plus pertinent de reprendre l'ensemble des chapitres de mise en main et d'y intégrer progressivement ggplot ?

**Comment by briatte** [comment]
Graphiques de base : je prolonge ton chapitre "stat. univariée" en montrant quelques exemples supplémentaires de visualisation de distribution (`density`, `ecdf`),  puis je donne quelques exemples de nuages de points (ce qui permet de préparer le lecteur au chapitre sur les stats. bivariées). Il n'y a presque aucune redite, et ça fait la jonction entre différents chapitres, en fournissant plus d'exemples, ce qui ne peut pas faire de mal :)

**Comment by larmarange** [comment]
Ca on peut le faire directement dans le chapitre Stat univariée.

Tu aurais 5 minutes pour un point Skype ?

**Comment by briatte** [comment]
Ouaip, `f.briatte` !

**Comment by larmarange** [comment]
ggplot va être abordé au travers de différents chapitres. Voir https://github.com/larmarange/analyse-R/wiki/Structure-du-texte

**Comment by briatte** [comment]
Yep.

En attendant, j'ai rajouté des idées sur le wiki, notamment l'idée qu'il serait bien de proposer un mix de données micro (individus) et macro (communes, pays), cross-section et panel.

**Comment by larmarange** [comment]
Cool

 Joseph
