### ISSUE TITLE
Intégration de dplyr

### ISSUE THREAD

**Issue by larmarange** [larmarange/analyse-R#24]
Ce serait un bon chapitre à ajouter. Par contre, je n'ai pas encore vraiment expérimenté ce package

**Comment by larmarange** [comment]
voir aussi https://github.com/joelgombin/presDplyr

http://www.r-bloggers.com/the-complete-catalog-of-argument-variations-of-select-in-dplyr/

**Comment by larmarange** [comment]
dplyr va être intégré dans les autres chapitres, dès Manipulation de données.

Voir si besoin de faire un chapitre avancé.

**Comment by briatte** [comment]
Certes, mais regarde le [wiki pour la structure du texte](https://github.com/larmarange/analyse-R/wiki/Structure-du-texte) : concrètement, il faut d'abord couvrir les fonctions de base pour mean, median, etc., et ensuite, passer à `dplyr`, où l'on peut assumer que le lecteur sait ce que veut dire `summary(mu = mean(x))`.

**Comment by larmarange** [comment]
Commentaire de @briatte (source https://github.com/larmarange/analyse-R/commit/91f6e0e2de3d0acdb97244197854aaa4995e6045)

Si tu regardes le wiki "structure", tu verras qu'en fait, je doute de plus en plus de l'utilité de passer immédiatement à des exemples avec haven/readr/dplyr. En réalité, la section "stats. intro." peut se passer de les introduire d'emblée (par exemple, l'utilisation de readr dans le chapitre ggplot2 est artificielle : aucun bénéfice, dplyr n'étant pas utilisé).

Je recommande du coup d'introduire les données libellées en fin de section, avant (ou après) les données pondérées, puis de rédiger les chapitres suivants avec ce bénéfice. Idem pour dplyr.

**Comment by briatte** [comment]
Cette suggestion permet notamment de garder les chapitres "stats. univariées" à "données pondérées" avec les exemples de `questionr`, puis d'introduire, en dernier dans la section "stats. intro.", les données libellées.

Comme ça, à la fin de "stats. intro.", le lecteur a tout vu : du R base, des données pondérées, des données libellées. Il y a largement la place dans stats. intermédiaires pour se servir de `dplyr` et des labels de `haven`.

**Comment by larmarange** [comment]
Il me semble qu'il faut distinguer d'une part l'import de données et d'autres part les fonctions de manipulation de données fournies par `dplyr` ou `reshape2`.

Concernant l'importation de données, j'aurais plutôt tendance à adopter une approche unifiée. Certes, dans ton chapitre introductif à `ggplot2` il n'y a pas de "gain" à utiliser `readr` mais il n'y a pas non plus de "pertes".  Quitte à apprendre une manière d'importer les données, autant apprendre l'approche `haven`/`readr`. Sinon cela revient à apprendre une manière de faire pour importer puis à la désapprendre pour réapprendre une autre manière de faire.

Le fait d'être confronté depuis le début à des données labellisées parmet aussi de distiller l'apprentissage à chacune des étapes. Dans _Manipulation de données_, on n'abordera pas _dplyr_. Effectivement, il vaut mieux l'aborder en fin de stats intro. Mais être confronté dès le début aux données labellisées me semble bon.

Cela permet également de vérifier leur gestion par `questionr` à chaque étape de Prise en main et de stats introductives. En effet, du fait de l'héritage de Julien, `questionr` est distillé à chaque étape, et non dans un chapitre ultérieur, où après avoir vu **R base**, on aborde les outils de `questionr`. Il s'agit bien d'aider l'utilisateur qui bascule de **SPSS** ou **Stata** à retrouver rapidement ses petits.

**Comment by larmarange** [comment]
Précision : le recours à des données labellisées est complètement indépendant de l'usage de `dplyr`

**Comment by briatte** [comment]
OK sur le coût très faible de `readr` : je le réintègre au chapitre ggplot2.

OK aussi sur les données labellisées. Si on les introduit en toute fin de chapitre (je suggèrerais même de les mettre après les données pondérées), ça me va.
