### ISSUE TITLE
Présentation des données labellisées dans les chapitres

### ISSUE THREAD

**Issue by larmarange** [larmarange/analyse-R#26]
Comment gérer des données avec des étiquettes. Voir haven, sjPlot, sjmisc... en particulier

**Comment by briatte** [comment]
:+1: 

Plus généralement, un chapitre "Données catégorielles" serait pertinent pour tous ceux qui bossent sur des données d'enquête.

**Comment by larmarange** [comment]
Les enjeux sont aussi à mon sens de pouvoir proposer une approche de travail. 

Pour ma part, je me rends compte que je travaille de plus en plus en important les codes numériques, et en transformant en facteurs au cas par cas pour les besoins de l'analyse.

D'ailleurs le package `haven` à adopter cette approche. Mais il faut encore qu'il se stabilise un peu. Les dates sont enfin importées correctement. Par contre, il y a encore débat sur l'import des valeurs manquantes déclarées, cf. https://github.com/hadley/haven/issues/33 ou https://github.com/hadley/haven/issues/82

Je me dis que ca vaudrait le coup de réfléchir un peu posément à tout ca, puis de reprendre le chapitre _Importer des données_ et même les chapitres d'analyses pour opter sur une démarche cohérente d'un chapitre à l'autre.

**Comment by briatte** [comment]
Une manière de structurer tout ça, c'est de se donner un ordre de préférence, exemples :
- graphiques : ggplot2 > lattice > base
- import / export : haven, readr, readxl > foreign > autres
- structures : data_frame > data.frame > matrix > autres

etc.

**Comment by larmarange** [comment]
> structures : data_frame > data.frame > matrix > autres

haha  the "hadleyword"

De mon côté, je suis plutôt un gros utilisateur de `data.table`. Heureusement, les deux sont compatibles.

**Comment by larmarange** [comment]
Histoire de noter des idées : https://github.com/larmarange/analyse-R/wiki/Carnet-de-d%C3%A9veloppement

**Comment by briatte** [comment]
Vu ; est-ce qu'on peut aussi basculer le fichier `conventions.txt` sur le wiki et ouvrir un thread de discussion dessus ?

**Comment by larmarange** [comment]
Bonne idée

 Joseph

**Comment by briatte** [comment]
C'est fait, [ma proposition est ici](https://github.com/larmarange/analyse-R/wiki/Conventions). Attention, il y a quelques grosses modifications.

**Comment by larmarange** [comment]
Je regarderai en détails demain.

Une précision sur les attributs pour les fonctions. Ils doivent
impérativement commencer par data- pour être valide en HTML.

Joseph Larmarange

**Comment by briatte** [comment]
OK, je corrige !

**Comment by larmarange** [comment]
J'ai fait quelques modifs : pour la classe package on peut raccourcir en
"pkg". Pour les fonctions, il me semble qu'on peut encore gagner une lettre
avec data-pkg.

 Joseph

2015-07-03 21:20 GMT+02:00 François notifications@github.com:

**Comment by briatte** [comment]
OK. Autant raccourcir aussi la doc, alors, à `data-doc`.

**Comment by larmarange** [comment]
Pas sûr. Le fait d'utiliser data-rdoc permet de bien se rappeler qu'on fait
référence à rdocumentation

 Joseph

2015-07-03 21:52 GMT+02:00 François notifications@github.com:

**Comment by briatte** [comment]
OK, on garde `rdoc`.

**Comment by larmarange** [comment]
Concernant la gestion des étiquettes, il pourrait être pertinent d'avoir un endroit où mettre des fonctions qui facilitent leur usage (certaines existent déjà dans https://github.com/sjPlot/sjmisc ).

Faudrait-il envisager de créer un package dédié ou bien les ajouter à https://github.com/juba/questionr ?

**Comment by briatte** [comment]
À mon avis, ça a sa place dans `questionr`, que je conçois personnellement comme un _package_ destiné à l'étudiant de L3 en sociologie qui a un fichier Excel de 30 à 300 individus, avec des variables presque exclusivement qualitatives, et qui veut faire (1) du recodage, (2) des jolis graphiques, et éventuellement (3) une ACM, en apprenant le strict minimum de fonctions et en installant le strict minimum de packages.

À voir avec @juba, bien sûr !

**Comment by larmarange** [comment]
Si je puis me permettre, **questionr** est tout aussi utile pour le chercheur chevronné LOL. `freq` est vraiment une fonction du quotidien pour explorer ses données.

Il y a la prise en compte des labels pour les tableaux de fréquence et la transformation des variables labellisés en facteurs. Et ça a tout a fait sa place dans questionr. Reste à savoir si on veut seulement une compatibilité avec **haven** ou aussi avec **foreign**. Pour ma part, je me suis déjà un peu amusé à explorer quelques fonctions (cf. https://github.com/larmarange/JLutils/blob/master/R/label_freq.R).

Il pourrait aussi y avoir une fonction du type `codebook` dans `questionr` et je pense que cela serait suffisant pour les besoins couverts par ce package.

Si on souhaite se donner le temps de la réflexion, on peut toujours tester dans `JLutils`.

**Comment by briatte** [comment]
Tout à fait d'accord sur `freq`. Je pense la même chose du package `fre` pour Stata.

On peut suivre l'exemple du package **memisc**, qui est entièrement compatible avec les objets SPSS importés via `foreign`. J'avais vu tes tests dans `JLutils`, ça me paraît aller dans la bonne direction.

**Comment by larmarange** [comment]
J'ai repris le chapitre _Premier travail avec les données_ (cf. https://github.com/larmarange/analyse-R/commit/c8fec65b8bf25e487f8effc38acf444aff48937b). Je suis revenu en arrière et il n'y a plus mention des données labellisées à ce stade.

Par contre, je pense commencer à aborder cette notion dans le chapitre _Manipulation de données_.

En effet, il y a une longue partie sur les facteurs. Je pense introduire les données labellisées juste après et comment les transformer en facteurs.

Par contre, je penser alléger ce chapitre. Je me dis qu'il serait pertinent de prévoir un chapitre _Manipulation de tableaux_ qui reprendrait `subset`, _tri de tableaux_, _fusion de tableaux_.  Et là, on peut commencer à introduire doucement `dplyr`.
