### ISSUE TITLE
Titre

### ISSUE THREAD

**Issue by briatte** [larmarange/analyse-R#40]
Allez, un dernier commentaire et j'arrête de pourrir tes issues pour aujourd'hui…

Vu les chapitres que tu prévois d'ajouter (réseaux, spatial, etc.), c'est de l'analyse de données plutôt que seulement des données d'enquêtes, non ?

Je profite de cette question pour dumper mon archive de trucs utiles pour R, qui contient des tonnes d'exemples (j'en ai d'autres sur disque dur, dans le [cours](http://f.briatte.org/teaching/ida/) que j'ai proposé de transposer en grande partie dans certains chapitres, et sur [Polit'bistro](http://politbistro.hypotheses.org/)) :

https://pinboard.in/u:phnk/t:r/

**Comment by larmarange** [comment]
C'est plutôt un plaisir de voir que ça intéresse du monde.

Pour moi, l'analyse spatiale, l'analyse de réseaux font aussi partie de l'analyse des données d'enquêtes...  (mais pas que c'est vrai) 

Il est vrai que le contour est parfois un peu flou. L'idée est grosso modo d'essayer de centraliser pas mal de choses en un même endroit, francophone, tout en essayant de rester un minimum structuré, et de suivre un peu les évolutions auour de **R** (et ca bouge pas mal !!!).

Après, comme toujours, le problème va être le temps disponible (c'est souvent par accoups). Mais si un petit groupe de personnes a envie de mutualiser ses idées, ca pourrait être pas mal.

**Comment by briatte** [comment]
> le problème va être le temps disponible

Oui :P

Conseil : mets un max. de monde sur le coup. Même si chacun n'a le temps qu'une seule fois par an, ça fera toujours un minimum d'activité sur le manuscrit, et ça assure aussi la diffusion (par exemple, si tu mets Pierre Mercklé dans la boucle, il signalera ça aux enseignants de "socio. quanti." réunis sur la liste de diffusion du même nom depuis quelques semaines).

Avoir beaucoup de monde permettra d'écrire tous les chapitres à plusieurs, voire d'avoir un système de relecteurs.
