### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by briatte** [larmarange/analyse-R#41]
Fil de discussion de [ce document](https://github.com/larmarange/analyse-R/wiki/Conventions).

**Comment by larmarange** [comment]
Concernant le cas particulier des variables (i.e. des noms de colonnes d'un data.frame) il me semble qu'il faut distinguer sémantique et mise en forme. 

Au niveau sémantique, il existe une balise **HTML** dédiée : `<var> ... </var>`.

Certes ca alourdit un peu l'écriture, mais le rendu **HTML** serait plus juste. En termes de mise en forme, on peut alors les cibler spécifiquement, ce qui permet d'appliquer une police monospace, mais de ne pas appliquer un background gris (comme pour `<code>`). On peut aussi garder un italique en plus de la police monospace.

**Comment by larmarange** [comment]
La convention ne précise pas comment écrire une classe d'objet. Vaut-il mieux utiliser `<var>` ou `<code>` ? (je me dis que le premier est peut être mieux)

**Comment by larmarange** [comment]
Tant qu'à être précis sur la sémantique, ne devrait-on pas utiliser `<em lang="en">...</em>` pour un mot en langue anglaise ?

**Comment by briatte** [comment]
> Au niveau sémantique, il existe une balise HTML dédiée : `<var> ... </var>`.

`<var>` me va très bien, je ne connaissais pas !

> Tant qu'à être précis sur la sémantique, ne devrait-on pas utiliser <em lang="en">...</em> pour un mot en langue anglaise ?

En réalité, c'est `<i lang="en">` qu'il faudrait utiliser, vu que les italiques ne signalent pas ici une emphase. Mais ça alourdirait vraiment le code source du texte, qui cesserait d'être lisible par endroits, sans bénéfice clair (sauf peut-être pour les liseuses).

**Comment by briatte** [comment]
Questions :
1. Est-ce que c'est gênant, pour la gestion des _packages_, de créer un lien dans la balise `<strong>` ? Exemple :
   
   `<strong class="package">[ggplot2](http://ggplot2.org/)</strong>`
2. Si ce n'est pas gênant, est-ce qu'il faut "discipliner" ces liens, en n'acceptant qu'une liste limitée de sites (CRAN, R-Forge, GitHub) ?

**Comment by larmarange** [comment]
Quel est l'objectif de ce lien pour les packages ?

**Comment by larmarange** [comment]
> 1. Est-ce que c'est gênant, pour la gestion des _packages_, de créer un lien dans la balise  `<strong>` ? Exemple :
>    
>    `<strong class="package">[ggplot2](http://ggplot2.org/)</strong>`

Oui c'est gênant pour la création de l'index des packages

**Comment by larmarange** [comment]
Autre point de convention à clarifier :

concernant les titres, jusque là il n'y a pas de marquage de nom de fonction ou de nom de package ==> le marquage sémantique ayant lieu dans le texte lui-même

cela évite des interférences avec les fonctions de création de table des matières

**Comment by larmarange** [comment]
Pour le changement de langue, je me demande si c'est pas plutôt une balise `span` qu'il faudrait utiliser cf. http://www.alsacreations.com/astuce/lire/1151-langue-du-contenu.html

Et bien sûr une balise `<cite>` s'il s'agit d'un titre de doc

**Comment by larmarange** [comment]
`<span>` est aussi recommandé sur cette page http://www.ic.gc.ca/eic/site/pt-te.nsf/fra/00329.html

**Comment by briatte** [comment]
OK, je retire les liens dans les balises `<strong>`. L'exemple de ggplot2 montre comment je m'en servais : pour faire référence à des sites supplémentaires.

Pour la langue, je sais que `<i>` n'est plus en vogue depuis `<em>` (càd. depuis 2004 environ), mais c'est fondamentalement la même chose que `<span>` tant que les navigateurs comprennent `<b>` et `<i>`, donc pour longtemps, je pense.

Concernant `<cite>` et `<q>`, est-ce que tu veux que je remplace les `« chevrons »` par des `<q>balises</q>`, y compris pour les `<cite>titres</cite>` ? Je ne l'ai pas fait, j'ai hard-codé les guillemets.

**Comment by larmarange** [comment]
Concernant les packages, un lien est automatiquement créé vers sa page rdocumentation. Bien sûr, il peut être pertinent de préciser un lien supplémentaire de documentation, mais cela peut se faire dans le texte (en dehors du strong) soit en note soit dans le corps de texte.

Il reste un cas particulier pour les packages qui ne sont pas documentés sur rdocumentation. Faut-il alors dans ces cas là aller jusqu'à proposer un attribut `data-url` pour spécier l'URL de son choix ? Auquel cas, il faudrait aussi proposer un tel attribut pour les fonctions.

Le `<i>` n'est plus en vogue car c'est une indication de mise en forme tandis qu'un `<span lang="en">` est une indication sémantique (et on peut ensuite appliquer en CSS une mise en forme italique).

Pour les titres d'ouvrage, `<cite>` est suffisant, pas besoin de guillemets. De même pour `<q>`. On peut toujours affiner ensuite le rendu en CSS. L'intérêt d'un balisage propre est de pouvoir effectuer plus facilement des post-traitements.

**Comment by larmarange** [comment]
J'essaie de mettre à jour le Wiki en même temps mais n'hésite pas à compléter.

**Comment by briatte** [comment]
OK sur tes points. Dernière question, pour un titre d'article, je mets `<cite><q>les deux</q></cite> ?

**Comment by briatte** [comment]
Wiki : je viens de rajouter la précision sur les titres (ne pas utiliser de markup).

Concernant `<span lang="en">`, ça va rendre le texte très, très lourd…

**Comment by larmarange** [comment]
> Concernant <span lang="en">, ça va rendre le texte très, très lourd…

Pas forcément, il suffit d'éviter les anglicismes. Les chapitres parlent ainsi d'extensions et non de packages. Et quand il s'agit d'un concep, on a recours à `dfn`

**Comment by larmarange** [comment]
Sinon, on adopte la solution de facilité : juste de l'italique de base, mais en markup mardown, ce qui donnera des em

**Comment by briatte** [comment]
Je serais partisan de la solution de facilité, ne serait-ce que pour éviter de devoir coder le mot _package_ partout.

Correction de ma question sur les titres d'articles : il faut faire `<q><cite>comme ça</cite></q>` ? Ça doit pouvoir se styler ensuite en CSS3 pour enlever l'italique.

**Comment by larmarange** [comment]
Un titre d'article c'est juste `cite`. `q` est utilisé pour citer une portion du texte

**Comment by briatte** [comment]
OK, mais comment tu styles un titre d;ouvrage et un titre d'article différemment ?

**Comment by larmarange** [comment]
On parle du corps du texte ou bien carrément de la mise en forme d'une référence biblio complète en note de bas de page ?

**Comment by briatte** [comment]
Du corps du texte : "dans leur article intitulé « Hello World », les chercheurs…".

**Comment by larmarange** [comment]
Dans le corps du texte, il est tout à fait valide d'utiliser de l'italique, et donc juste `<cite>`.

**Comment by briatte** [comment]
OK !
