### ISSUE TITLE
Import de données et readr

### ISSUE THREAD

**Issue by larmarange** [larmarange/analyse-R#44]
Aujourd'hui `readr` a un problème majeur en termes d'encodage des caractères.

cf. https://github.com/hadley/readr/issues/40

Il est préférable d'attendre que ce problème soit fixé avant de baser la section _fichiers textes_ du chapitre _Import/Export_ de données sur `readr`

**Comment by larmarange** [comment]
Eléments de réponse

https://github.com/hadley/readr/issues/40#issuecomment-139058791

**Comment by briatte** [comment]
`readr` présente aussi l'inconvénient d'être un peu trop méchant sur les dates : `1940-06` sera trop rapidement compris comme `yyyy-mm-dd` et converti en `NA`. J'évite aussi de m'en servir pour le moment, sauf en de rares occasions où les données sont très larges et où la vitesse de lecture est importante.

**Comment by larmarange** [comment]
Oui, il est encore préférable d'attendre.

Il y a bp de commits en ce momemnt sur `readr`. Il faudra voir ce que donne la prochaine version stable.
