### ISSUE TITLE
Structure du site

### ISSUE THREAD

**Issue by larmarange** [larmarange/analyse-R#45]
Discussion de la structure du site

En lien avec le wiki https://github.com/larmarange/analyse-R/wiki/Structure-du-texte

**Comment by larmarange** [comment]
Je me demande si on ne pourrait revoir la structure du site avec trois grandes entrées : Manipuler, Analyser, Approfondir

Le site serait alors divisé ainsi :

**Manipuler**
- _Prise en main_
  - Présentation et Installation
  - Premier contact
  - Premier travail avec les données
  - Organiser ses fichiers
  - Import/Export de données
  - Variables
  - Indexation
  - Recodages
  - Exporter des graphiques
  - Où trouver de l'aide ?
- _Manipulation des données (intermédiare)_
  - Introduction à dplyr
  - Introduction à data.table
  - Doublons et valeurs uniques
  - Tris
  - Sous-populations
  - Fusion de tables
- _Manipulation des données (avancé)_
  - Aggrégation
  - Fonctions à fenêtre
  - Remodelage des données (reshape...)
  - Manipulation du texte (stringr, stringi)
  - Bases de données SQL
  - récupération de données web

NB : les chapitres de la sous-section _Manipulation des données_ présenteraient à la fois, pour chaque type de problème, **R base**, **dplyr**, **data.table**.

**Analyser**
- _Statistiques introductives_
- _Statistiques intermédiaires_
- _Statisques avancées_

**Aprofondir**
- _Programmation_
  - Formules ou la notation "équation"
  - Structures conditionnelles
  - Expressions régulières
  - Ecrire ses propres fonctions
  - Shiny et les interfaces interactives
  - Lubridate et la gestion des dates
  - RStudio et Git
  - Ecrire un package
- _Graphiques_
  - ggplot2 avancé
  - diagrammes
  - représenter des flux
  - réseaux dynamiques
  - ggvis et les graphiques interactifs
- _Exemples d'analyse_
  - ....
- _Astuces_
  - Calculer un âge
  - ... 

Il y aurait donc du débutant et de l'avancé dans chaque section.

On indiquerai en page d'accueil que pour ceux débutant avec R, on les invite à lire en tout premier lieu la sous-section _Prise en main_ de **Manipuler** puis la sous-section _Statistiques introductives_ de la section **Analyser**.

**Comment by larmarange** [comment]
@briatte  

En un sens, cela amène une structure globale systématiquement en sections et sous-sections. Avec trois grandes entrées indiquées par des verbes ce qui fait qqch de plus dynamique.

Dans la foulée, je supprimerai bien le bouton **Accueil** car il fait doublon dans le menu avec **analyse-R** qui renvoie aussi vers l'accueil.

Je regrouperai bien les index et le PDF sous une même entrée **Naviguer** ou **Chercher**. Ou pourrait même y déplacer le chapitre _Où trouver de l'aide ?_.

Enfin, il y aurait assez de place pour ramener **Participer** dans le menu principal. Est-ce que le terme **Contribuer** serait plus approprié ? On pourrait rajouter une page expliquant les différentes manières de participer (forums, indiquer les bugs et les coquilles, proposer des chapitres, etc.)

**Comment by briatte** [comment]
Comme je viens juste de découvrir la structure actuelle, j'ai du mal à me projeter dans une autre. Celle-ci me semble plus difficile d'accès.

> Dans la foulée, je supprimerai bien le bouton Accueil car il fait doublon dans le menu avec analyse-R qui renvoie aussi vers l'accueil.

OK.

> Enfin, il y aurait assez de place pour ramener Participer dans le menu principal. Est-ce que le terme Contribuer serait plus approprié ? On pourrait rajouter une page expliquant les différentes manières de participer (forums, indiquer les bugs et les coquilles, proposer des chapitres, etc.)

"Contribuer" plutôt que "Participer" : :+1: 

Ramener dans le menu principal : personnellement, je le trouve bien tout à droite. En revanche, le sous-menu n'est pas utile : un lien simple vers GitHub suffirait, sauf si tu veux rajouter une page "Comment aider", ce qui peut être une bonne idée.

**Comment by larmarange** [comment]
Je viens de regarder rapidement la table des matières de _R Cookbook_, _R for everyone_ et _R in action_.  Tout ce qui est manipulation de données (y compris avancée) est présenté avant l'analyse.

La difficulté est de concilier utilisateur débutant et utilisateur avancé. Mais il ne me semble pas problématique que l'ordre d'un cours ne soit pas forcément l'ordre d'un manuel.

Je vais laisser passer la nuit et j'essaie de préparer une réorga du site demain soir.

**Comment by briatte** [comment]
Je suis fan des [mêmes bouquins que toi](http://f.briatte.org/teaching/ida/002_readings.html), mais comme tu dis, la difficulté est de rendre le texte utile pour tout le monde. Je serais d'avis d'organiser le texte pour des débutants, et de laisser les utilisateurs avancés se débrouiller pour trouver ce qui les intéresse — dans les sections Analyse et Extras, principalement.

**Comment by larmarange** [comment]
Tout ce qui est du domaine de la manipulation de données est centrale et n'a pas sa place en tant que tel dans la section Analyses. Il faut une section dédiée. 

Toute la partie prise en main relève soit de la manipulation du logiciel, soit de la manipulation des données.

Pour un débutant, l'ordre "chronologique" serait de l'ordre: 
- prise en main de l'outil et manipulations de bases
- statistiques introductives
- manipulation de données intermédiaires
- statistiques intermédiaires
- manipulation de données avancées
- statistiques avancées
- approfondissements

Dans le cadre d'un cours, on fait la navette entre les deux. C'est justement l'idée d'une structuration en sections et sous-sections. Deux grands pôles Manipuler / Analyser et à chaque fois une progression intro / intermédiaire / avancé

**Comment by larmarange** [comment]
Une alternatie pourrait être une structuration en 
- Débutant
  - Prise en main
  - Statistiques introductives
- Intermédiaire
  - Manipulation de données
  - Statistiques intermédiaires
  - Programmation intermédiaire
- Avancé
  - Manipulation de données
  - Statistiques avancées
  - Programmation avancée
  - Graphiques
- Divers
  - Astuces
  - Exemples d'analyse

**Comment by larmarange** [comment]
J'ai un peu discuté avec différents collègues ce matin pour avour un feedback un peu extérieur.

Dans ce qu'il en ressort, c'est tout d'abord que lorsqu'on arrive sur un tel site avec un besoin donné il est préférabe d'avoir une aborescence thématique qui répond à la question <q>Qu'est ce que je veux faire ?</q>. Dès lors une structuration de premier niveau du type Débutant / Intermédiaire / Avancé ne serait pas pertinente car on ne saurait pas _a priori_ ce qui appartiendra à chaque niveau.  L'approche Manipuler / Analyser / Approfondir s'avère ici plus pertinente.

Par contre, il faut également fournir un parcours facile à suivre pour quelqu'un qui découvre tout juste **R**. Cela peut se faire à la fois avec des intitulés de sous-sections explicites et avec, en page d'accueil, un parcours proposé aux personnes qui débutent avec **R**.

**Comment by larmarange** [comment]
Voilà, j'ai repris en détail la page https://github.com/larmarange/analyse-R/wiki/Structure-du-texte

Je me lance dans la restructuration des fichiers dans la soirée.

**Comment by briatte** [comment]
J'ai lu le wiki, ça a l'air bien !

**Comment by larmarange** [comment]
OK.

Je viens d'envoyer un gros lot de commits. La nouvelle structure du site est en place. J'en ai profité pour créer de nombreux chapitres vides (avec un warning). Mais comme ça la structure est en place et on peut déjà faire des liens internes lors de l'écriture.

Ce fut d'ailleurs une bonne idée car cela m'a permis de voir qu'il fallait réorganiser les menus (qui sont maintenant sur 3 colonnes). J'en ai aussi profité pour générer programmatiquement le menu de la page d'accueil.

Sur la page d'accueil, un parcours de lecture est proposé aux débutants.

J'ai aussi réorganisé les préfixes des fichiers et le rangement des figures créées par `knitr` en dossiers et sous-dossiers. **ATTENTION :**  les captures d'écran doivent rester à la racine de `images/` car `images/manipuler`, `images/analyser` et `images/approfondir` sont supprimés par le script `Makefile` avant d'être regénérés.

**Comment by briatte** [comment]
Looks good!

Le PDF est trop difficile à trouver ; je serais d'avis de pousser "Contribuer" à droite comme avant (avec une petit icône GitHub ?), et de mettre un lien direct "Télécharger (PDF)" (ou "Télécharger" avec une icône PDF ?) vers le PDF à la place.

"Naviguer" pourrait s'appeler "Index".

La ligne "Accueil … Développement … analyse-R en PDF" me paraît redondante avec les menus. N'indiquer que la licence suffirait.

Est-ce qu'il y a moyen, dans les menus déroulants, de montrer l'état d'avancement des chapitres, pour distinguer ce qui est déjà rédigé du reste ?

**Comment by larmarange** [comment]
> Est-ce qu'il y a moyen, dans les menus déroulants, de montrer l'état d'avancement des chapitres, pour distinguer ce qui est déjà rédigé du reste ?

Tu penses à quel type de visuel ? Fond coloré uniquement ou plus ?

**Comment by briatte** [comment]
Un fond coloré suffirait à repérer ce qui est déjà lisible.

**Comment by larmarange** [comment]
> Le PDF est trop difficile à trouver ; je serais d'avis de pousser "Contribuer" à droite comme avant (avec une petit icône GitHub ?), et de mettre un lien direct "Télécharger (PDF)" (ou "Télécharger" avec une icône PDF ?) vers le PDF à la place.

Une première remarque générale, le site responsive, donc il faut penser à regarder ce que ça donne quand on redimensionne la largeur. ;-)

Quitte à pousser à droite, pourquoi ne pas mettre directement un GitHub Ribbons cf. https://github.com/blog/273-github-ribbons que l'on masquerai sur petit écran ?

Il faut essayer de garder un peu de place pour pouvoir rajouter un champs de recherche.

Pour le PDF, est-ce que juste le texte PDF n'est pas suffisant ?

**Comment by briatte** [comment]
Ribbon : ça me va.

"PDF" suffirait, oui.

**Comment by larmarange** [comment]
OK

je viens de committer les modifs demandées

**Comment by briatte** [comment]
"Exporter des graphiques" est en double
- chapitre dans la partie "PEM"
- sous-chapitre dans "stats. intro. > graphes univ."

Lequel te paraît le plus approprié ?

**Comment by larmarange** [comment]
A mon sens, il est préférable que ca apparisse en clair dans le menu, donc dans PEM. Il suffit de faire un renvoi dans graph univ. (au besoin on peut garder 3-4 lignes dans graph_univ, puisque la redite n'est pas un souci)

**Comment by briatte** [comment]
Je comprends, mais en même temps, aucune section avant "Exporter des graphiques" ne produit de graphiques, non ?

**Comment by larmarange** [comment]
Il suffit de déplacer au début de manipulation de données (intermédiaires) ?

 Joseph

2015-07-07 22:36 GMT+02:00 François notifications@github.com:

**Comment by larmarange** [comment]
Et dans graph univarié juste aborder le bouton exporter de RStudio, sans rentrer dans les détails sur le type d'images

**Comment by briatte** [comment]
> Il suffit de déplacer au début de manipulation de données (intermédiaires) ?

C'est pas vraiment intermédiaire, sauf si on fait un truc complet en expliquant aussi comment paramétrer les dimensions et la résolution des graphiques.

À la rigueur, je dirais : à la toute fin de "stats. intro.", en rajoutant aussi un chapitre sur "Exporter des tableaux", ce qui serait très utile, au passage.

J'aurais également tendance à placer "Interv. de confiance" et "Comp. de moyennes/props" dans "Stats. intro.", après "Données pondérées".

**Comment by larmarange** [comment]
Je suis d'accord pour intervalles de confiance et comparaisons.

Pour ce qui est des exports de graphiques et de tableaux, cela relève
clairement de Manipuler et pas d'Analyser. Il faut que ces informations
soient accessibles dans le cadre des entrées thématiques ce qui n'empêche
pas que cela puisse aussi être présenté (plus succinctement) dans les
chapitres analytiques correspondants (tout comme il y a des graphiques dans
stats univariées même si c'est complété ensuite dans un chapitre plus
important).

Faudrait-il une sous-section supplémentaire Exporter dans Manipuler, avec
Exports de données, Export de graphiques, Export de tableaux ?

 Joseph

**Comment by briatte** [comment]
Ce serait une bonne idée ! J'exporte tout avec `xtable` mais je sais que ce n'est pas la seule solution.

**Comment by larmarange** [comment]
Juste pour simplifier (et éviter d'avoir 4 sections dans Manipuler), que
dirais-tu de :
- fusionner Manipulation de données intermédiaires et avancées
- créer une troisième section Exporter
  
  Joseph

2015-07-08 13:48 GMT+02:00 François notifications@github.com:

**Comment by briatte** [comment]
Ça me va !

**Comment by larmarange** [comment]
section exporter crée.  Je te laisse faire le renommage des fichiers et le js du menu quand tu pourras

**Comment by larmarange** [comment]
Je viens de procéder au renommage des fichiers. Au passage, plus besoin de préciser le répertoires des graphiques (c'est auto). Et le menu fonctionne

**Comment by briatte** [comment]
Nickel !

**Comment by larmarange** [comment]
Pour info, je viens de procéder à une réorga de la partie prise en main, suite à des sessions de formation que j'ai réalisée en Afrique du Sud. Un peu moins de technique dans premier travail avec les données, mais ajout de quelques calculs et graphiques simples pour mieux voir les possibilités de **R**. Puis 3 chapitres qui reprennent les objets de base et l'indexation. Il me reste la partie _Recodage_ à compléter et la section _Prise en main_ devrait être complète.
