### ISSUE TITLE
Graphiques données libellées

### ISSUE THREAD

**Issue by larmarange** [larmarange/analyse-R#47]
@briatte 

Que souhaite-tu mettre dedans ?

S'il s'agit juste de convertir en facteur avec les labels, y a pas besoin d'un chapitre dédié.

Ou est-ce que tu veux faire référence au package sjPlot?

**Comment by briatte** [comment]
Les deux me semblent utiles, en particulier si sjPlot est à un niveau de développement suffisant (je n'ai pas suivi).
