### ISSUE TITLE
Ajout moteur de recherche

### ISSUE THREAD

**Issue by larmarange** [larmarange/analyse-R#48]
cf. https://duckduckgo.com/search_box

Il faudra néanmoins attendre une indexation de analyse-R par bing (demande effectuée aujourd'hui).

Sinon, il y a aussi l'option Google (mais ca pose le problème des données personnelles).

**Comment by larmarange** [comment]
cf. https://github.com/larmarange/analyse-R/commit/210acc3c3fa382499c3f2d15ae6e487be6749ae2

**Comment by briatte** [comment]
Joli. Si j'étais toi, je laisserais un peu plus d'espace entre "PDF" et le formulaire.
