### ISSUE TITLE
astuce : Plotting regression curves with confidence intervals for LM, GLM and GLMM in R

### ISSUE THREAD

**Issue by larmarange** [larmarange/analyse-R#62]
à reprendre ? citer ?

http://www.r-bloggers.com/plotting-regression-curves-with-confidence-intervals-for-lm-glm-and-glmm-in-r/

**Comment by briatte** [comment]
Plus généralement, il faudra penser à une section "Obtenir des résultats graphiques à partir de modèles statistiques". Ce package est particulièrement recommandable :

https://cran.rstudio.com/web/packages/ggfortify/

**Comment by larmarange** [comment]
Utiliser plutôt broom : https://cran.r-project.org/web/packages/broom/index.html qui remplace ggfortify

Mettre à jour la page régression logistique, ainsi que graphiques bivariés à partir de broom

**Comment by larmarange** [comment]
Aussi parler de http://www.r-bloggers.com/evaluating-logistic-regression-models/
