### ISSUE TITLE
Astuces graphiques GGplot

### ISSUE THREAD

**Issue by larmarange** [larmarange/analyse-R#63]
- Eviter la superposition d'étiquettes : https://github.com/slowkow/ggrepel

**Comment by briatte** [comment]
Yep, j'ai vu ça aussi quand c'est sorti, c'est clair qu'il faudra l'intégrer ; désolé de ne pas avoir pu contribuer depuis longtemps, je ne vais pas pouvoir faire quoi que ce soit avant l'été, mais je revendrai donner un coup de main sur le repo avec plaisir dès que j'aurai le temps !

Cheers dude, keep up the good work.

**Comment by larmarange** [comment]
Merci François. Ne t'inquiète pas. Je n'ai moi même pas eu le temps d'avancer depuis de longs mois. J'essaie juste d'ouvrir des tickets afin de noter ce qu'il y aurait à intégrer.

Amitiés
