### ISSUE TITLE
Régression logistique

### ISSUE THREAD

**Issue by isaboc76** [larmarange/analyse-R#64]
Bonjour,
J'ai lu la partie sur la régression logistique.
J'aurais aimé savoir comment on pourrait intégrer une pondération sur les données utilisées ?
Merci d'avance

**Comment by larmarange** [comment]
Vous pouvez avoir recours au package **survey**. Je vous invite à lire cette page : http://larmarange.github.io/analyse-R/donnees-ponderees.html

Bien cordialement

**Comment by isaboc76** [comment]
Merci !
