### ISSUE TITLE
Parallélisation de calcul sous R

### ISSUE THREAD

**Issue by isaboc76** [larmarange/analyse-R#65]
Bonjour,
Avez-vous déjà expérimenté la parallélisation sous R ?
Merci d'avance.
A+
Isabelle

**Comment by larmarange** [comment]
Bonjour, je n'ai pas encore eu cette occasion.

**Comment by 3wen** [comment]
Bonjour,

J'avais commencé à aborder cet aspect il y a deux ans, en m'appuyant sur cette référence : http://shop.oreilly.com/product/0636920021421.do

C'est peut-être un peu trop daté...

**Comment by larmarange** [comment]
Trop spécfique pour analyse-R a priori
