### ISSUE TITLE
survey et calcul des poids de pondération.

### ISSUE THREAD

**Issue by hedjour** [larmarange/analyse-R#81]
Bonjour,
Dans le chapitre sur les données pondérées vous utilisez des poids ?
Comment peut-on calculer ces poids dans R ?
Merci

**Comment by larmarange** [comment]
Le calcul des poids se fait la probabilité d'inclusion. Je vous renvoie à la documentation du package survey.

Cdlt

**Comment by hedjour** [comment]
Si je cherchais la réponse dans votre ouvrage c'est justement parce que je ne comprennais pas la documentation vers laquelle vous me renvoyez ...
Sinon un paquet qu'il peut être bon de présenter : https://github.com/haroine/icarus
