### ISSUE TITLE
Suppression liens RDocumentation

### ISSUE THREAD

**Issue by even4void** [larmarange/analyse-R#97]
Avec les récents "événements" liés à DC, il serait peut-être judicieux de remplacer les auto-liens de documentation (`include/after_body.html`) vers une autre source d'aide en ligne. A priori, <https://rdrr.io> semble le meilleur candidat même si la dernière fois que j'avais essayé la couverture n'était pas aussi complète que <https://www.rdocumentation.org>.

**Comment by larmarange** [comment]
Bonjour, 

je n'ai pas suivi cette actualité. De quoi s'agit-il ?

Oui, il devrait être possible de modifier les liens de docs. Peut-être renvoyer par défaut vers la version CRAN et, au besoin, ajouter un paramètre pour la doc des packages GitHub

**Comment by briatte** [comment]
https://juliasilge.com/blog/datacamp-misconduct/

Rdrr.io est hélas moins complet, mais dans les deux cas, je trouve ces deux sites moins efficaces que __cran xyz__ dans Google (ou DuckDuckGo) ou __language:r xyz__ dans GitHub (ou l'équivalent dans StackOverflow et Cross Validated).

**Comment by larmarange** [comment]
Je viens de faire quelques essais, mais je rencontre un problème avec la manière dont https://rdrr.io/ génère les URL des liens de documentation.  En effet, cela ne respecte pas le `rdname` des pages de documentation. Prenons l'exemple de `svytable` et `svychisq`. Ces deux fonctions sont sur la même page de documentation qui correspond au rdname **svytable** comme on peut le voir dans l'aide en ligne intégrée. 

Les liens de documentation correspondant sont :

- https://www.rdocumentation.org/packages/survey/versions/3.35-1/topics/svytable
- https://rdrr.io/cran/survey/man/svychisq.html

A noter que rdocumentation fournit un permalink qui est http://www.rdocumentation.org/packages/survey/functions/svytable et qui renvoie directement sur la dernière version du package.  A noter que le lien http://www.rdocumentation.org/packages/survey/functions/svychisq fonctionne également et renvoie sur la bonne page. Et c'est ce type de lien qui est utilisé sur analyse-R.

Bref, en l'état, si on fait le changement, de nombreux liens de documentation ne seront pas valable et il faudrait aller les vérifier un à un !!!

**Comment by larmarange** [comment]
Il semble que des permalinks sont en cours de création. Discussion ouverte sur https://github.com/rdrr-io/rdrr-issues/issues/40

**Comment by even4void** [comment]
Je ne pense pas qu'il y ait réellement urgence de ce côté de toute façon. On verra comment les choses évoluent du côté de DC. J'avais rencontré des difficultés avec `rdrr` quand j'avais voulu l'utiliser, notamment sur le (dé)couplage package/fonction.

**Comment by briatte** [comment]
Je trouve les deux sites bordéliques au possible…

Par exemple, si je sais que Colin Fay a codé une fonction `stop_if_not`, comment demander à Rdrr de me trouver ça plutôt que [*toutes* les fonctions `stop_if_not` __et__ *tous* les packages de ColinFay](https://rdrr.io/search?q=colinfay+stop_if_not) ?

Ce n'est pas très constructif, je sais.

**Comment by larmarange** [comment]
On peut maintenant utiliser `https://rdrr.io/pkg/<package name>/sym/<symbol>` qui redirige directement vers la bonne page.
